### ISSUE TITLE
PRN.NetworkRole doesn't exist

### ISSUE THREAD

**Issue by Maclay74** [TCleard/PredictionReconciliationNetwork#3]
According to the documentation, it should
```cs
PRN.NetworkRole role;
        if (IsServer) {
            role = IsOwner? PRN.NetworkRole.HOST: PRN.NetworkRole.SERVER;
        } else {
            role = IsOwner ? PRN.NetworkRole.OWNER: PRN.NetworkRole.CLIENT;
        }
```

but it doesn't. Apparently, it was replaced by PRN.Actor.Actor?

**Comment by Maclay74** [comment]
`PRN.NetworkHandler` doesn't exist too, so there are four actors to replace it with different constructors.

I can't understand how to add these events now
```cs
networkHandler.onSendInputToServer += SendInputServerRpc;
networkHandler.onSendStateToClient += SendStateClientRpc;
```

UPD:
Oh, so everything is now in `Network` namespace. 
` PRN.Network.NetworkRole role` and `PRN.Network.NetworkHandler` accordingly.

**Comment by TCleard** [comment]
Your last comment says it all, there was a Network namespace under PRN. Now that you point it, it feels useless and redundant with the 2 classes prefix, NetworkHandler and NetworkRole. 
Those 2 classes are now directly under PRN namespace, so it matches the readme.
Thank you for pointing this out ;)
