### ISSUE TITLE
Interface names do not begin with 'I'

### ISSUE THREAD

**Issue by angusmf** [TCleard/PredictionReconciliationNetwork#8]
Minor thing, but if it weren't for the fact that some classes inherit multiple, I would have assumed these were classes. I'm happy to do a PR for it if it would be accepted

**Comment by TCleard** [comment]
I don't mind if you do ! If it's a standard / best practice for C# development, go for it ;)

**Comment by TCleard** [comment]
Fixed in [PR 9](https://github.com/TCleard/PredictionReconciliationNetwork/pull/9)
